dependencies:
  - name: postgresql
    alias: caliberBatchPostgresService
    version: 8.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: caliberBatchPostgresService.enabled